name: plotly
version: 0.0.6
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Interactive, browser-based charting library
homepage: https://github.com/rwl/plotly
dev_dependencies:
  browser: any
